const books = [
  {
    title: 'Mythos: The Greek Myths Retold',
    author: 'Stephen Fry',
    rating: 4,
    date: '2025-10-31',
    image: 'bs-mythos.jpg',
    cover: 'bc-mythos.jpg',
    height: '7.8',
  },
  {
    title: 'Норвежский лес',
    author: 'Харуки Мураками',
    rating: 4,
    date: '2025-09-30',
    image: 'bs-norwegian-wood.jpg',
    cover: 'bc-norwegian-wood.jpeg',
    height: '7.87',
  },
  {
    title: 'Chess Story',
    author: 'Stefan Zweig',
    rating: 4,
    date: '2025-08-10',
    image: 'bs-chess-story.jpg',
    cover: 'bc-chess-story.jpg',
    height: '7.97',
  },
  {
    title:
      'Atomic Habits: An Easy and Proven Way to Build Good Habits and Break Bad Ones',
    author: 'James Clear',
    rating: 4,
    date: '2025-07-20',
    image: 'bs-atomic-habits.png',
    cover: 'bc-atomic-habits.png',
    height: '8.46',
  },
  {
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    rating: 5,
    date: '2025-05-22',
    image: 'bs-project-hail-mary.jpg',
    cover: 'bc-project-hail-mary.jpg',
    height: '9.6',
  },
  {
    title: 'Что мой сын должен знать об устройстве этого мира',
    author: 'Фредрик Бакман',
    rating: 3,
    date: '2025-04-23',
    image: 'bs-things-my-son-needs-to-know-about-the-world.jpg',
    cover: 'bc-things-my-son-needs-to-know-about-the-world.jpg',
    height: '7.087',
  },
  {
    title: 'Маус',
    author: 'Арт Шпигельман',
    rating: 4,
    date: '2025-04-06',
    image: 'bs-maus.jpg',
    cover: 'bc-maus.jpg',
    height: '9.45',
  },
  {
    title: 'Табия тридцать два',
    author: 'Алексей Конаков',
    rating: 3,
    date: '2025-03-22',
    image: 'bs-tabiya-tridtsat-dva.jpg',
    cover: 'bc-tabiya-tridtsat-dva.jpeg',
    height: '8.31',
  },
  {
    title: 'Попытка к бегству',
    author: 'А.&nbsp;Стругацкий, Б.&nbsp;Стругацкий',
    rating: 3,
    date: '2025-02-28',
    image: 'bs-popytka-k-begstvu.jpeg',
    cover: 'bc-popytka-k-begstvu.jpeg',
    height: '6.5',
  },
  {
    title: 'Саша, привет!',
    author: 'Дмитрий Данилов',
    rating: 3,
    date: '2025-02-08',
    image: 'bs-sasha-privet.png',
    cover: 'bc-sasha-privet.jpg',
    height: '8.15',
  },
  {
    title: 'Как жить. Уроки стоицизма от Эпиктета, Сенеки и&nbsp;Марка Аврелия',
    author: 'Джон Селларс',
    rating: 3,
    date: '2025-01-25',
    image: 'bs-kak-jit.png',
    cover: 'bc-kak-jit.jpg',
    height: '7.09',
  },
  {
    title: 'Дары волхвов',
    author: 'О.&nbsp;Генри',
    rating: 3,
    date: '2025-01-01',
    image: 'bs-dary-volkhvov.jpg',
    cover: 'bc-dary-volkhvov.jpg',
    height: '7.87',
  },
  {
    title: 'Вторая жизнь Уве',
    author: 'Фредрик Бакман',
    rating: 4,
    date: '2024-12-29',
    image: 'bs-a-man-called-ove.jpg',
    cover: 'bc-a-man-called-ove.jpg',
    height: '7.87',
  },
  {
    title: 'Крестный отец',
    author: 'Марио Пьюзо',
    rating: 4,
    date: '2024-09-22',
    image: 'bs-godfather.jpg',
    cover: 'bc-godfather.jpg',
    height: '7.87',
  },
  {
    title: 'Потрясающие приключения Кавалера &amp;&nbsp;Клея',
    author: 'Майкл Шейбон',
    rating: 4,
    date: '2024-09-06',
    image: 'bs-kavaler-clay.png',
    cover: 'bc-kavaler-clay.jpg',
    height: '8.27',
  },
  {
    title:
      'Империя должна умереть: История русских революций в&nbsp;лицах. 1900-1917',
    author: 'Михаил Зыгарь',
    rating: 3,
    date: '2024-03-07',
    image: 'bs-empire-must-die.png',
    cover: 'bc-empire-must-die.jpg',
    height: '8.5',
  },
  {
    title: 'Silo. Dust',
    author: 'Hugh Howey',
    rating: 4,
    date: '2024-01-12',
    image: 'bs-silo-dust.png',
    cover: 'bc-dust.jpg',
    height: '8.00',
  },
  {
    title: 'Бункер. Смена',
    author: 'Хью Хауи',
    rating: 4,
    date: '2023-12-13',
    image: 'bs-bunker-change.png',
    cover: 'bc-bunker-change.jpg',
    height: '8.11',
  },
  {
    title: 'Бункер. Иллюзия',
    author: 'Хью Хауи',
    rating: 4,
    date: '2023-08-18',
    image: 'bs-bunker-illusion.png',
    cover: 'bc-bunker-illusion.jpg',
    height: '8.11',
  },
  {
    title: 'Защита Лужина',
    author: 'Владимир Набоков',
    rating: 3,
    date: '2022-07-31',
    image: 'bs-luzin.png',
    cover: 'bc-luzin.jpg',
    height: '8.19',
  },
  {
    title: 'Конец Вечности',
    author: 'Айзек Азимов',
    rating: 5,
    date: '2022-06-09',
    image: 'bs-end-of-eternity.jpg',
    cover: 'bc-end-of-eternity.jpg',
    height: '8.11',
  },
  {
    title: 'Палата №6',
    author: 'Антон Чехов',
    rating: 4,
    date: '2022-01-14',
    image: 'bs-palata-6.jpg',
    cover: 'bc-palata-6.jpg',
    height: '7.87',
  },
  {
    title: 'О&nbsp;чем я&nbsp;говорю, когда говорю о&nbsp;беге',
    author: 'Харуки Мураками',
    rating: 5,
    date: '2021-12-01',
    image: 'bs-beg.png',
    cover: 'bc-beg.jpg',
    height: '7.87',
  },
  {
    title: 'Ложная слепота',
    author: 'Питер Уоттс',
    rating: 4,
    date: '2019-08-24',
    image: 'bs-blindsight.jpeg',
    cover: 'bc-blindsight.jpeg',
    height: '8.07',
  },
  {
    title: 'Географ глобус пропил',
    author: 'Алексей Иванов',
    rating: 5,
    date: '2019-06-11',
    image: 'bs-geograf.png',
    cover: 'bc-geograf.jpg',
    height: '8.35',
  },
  {
    title: 'Имею скафандр – готов путешествовать!',
    author: 'Роберт Хайнлайн',
    rating: 5,
    date: '2019-02-08',
    image: 'bs-skafandr.png',
    cover: 'bc-skafandr.jpg',
    height: '6.5',
  },
  {
    title: 'Девять принцев Амбера',
    author: 'Роджер Желязны',
    rating: 3,
    date: '2018-12-01',
    image: 'bs-9-amber.png',
    cover: 'bc-9-amber.jpg',
    height: '8.19',
  },
  {
    title: 'Вы, конечно, шутите, мистер Фейнман!',
    author: 'Ричард Ф.&nbsp;Фейнман',
    rating: 5,
    date: '2018-08-13',
    image: 'bs-feynman.webp',
    cover: 'bc-feynman.jpeg',
    height: '7.08',
  },
  {
    title: 'Первому игроку приготовиться',
    author: 'Эрнест Клайн',
    rating: 4,
    date: '2017-11-15',
    image: 'bs-ready-player-one.jpeg',
    cover: 'bc-ready-player-one.jpeg',
    height: '7.87',
  },
  {
    title: 'Финансист',
    author: 'Теодор Драйзер',
    rating: 3,
    date: '2017-05-15',
    image: 'bs-finansist.jpg',
    cover: 'bc-finansist.jpg',
    height: '7.87',
  },
  {
    title: 'Источник',
    author: 'Айн Рэнд',
    rating: 4,
    date: '2017-03-18',
    image: 'bs-istochnik.png',
    cover: 'bc-istochnik.jpg',
    height: '8.27',
  },
  {
    title: 'Игра престолов',
    author: 'Джордж Мартин',
    rating: 4,
    date: '2016-09-10',
    image: 'bs-game-of-thrones.png',
    cover: 'bc-game-of-thrones.jpeg',
    height: '8.54',
  },
  {
    title: 'Вся кремлевская рать. Краткая история современной России',
    author: 'Михаил Зыгарь',
    rating: 3,
    date: '2016-04-01',
    image: 'bs-vsya-kremlevskaya-rat.png',
    cover: 'bc-vsya-kremlevskaya-rat.jpeg',
    height: '8.5',
  },
  {
    title: 'Гарри Поттер и&nbsp;Методы рационального мышления',
    author: 'Элиезер Юдковски',
    rating: 5,
    date: '2016-03-01',
    image: 'bs-hpmor.png',
    cover: 'bc-hpmor.jpg',
    height: '8.27',
  },
  {
    title: 'Автостопом по&nbsp;Галактике',
    author: 'Дуглас Адамс',
    rating: 3,
    date: '2015-12-01',
    image: 'bs-autostop.png',
    cover: 'bc-autostop.jpg',
    height: '7.087',
  },
  {
    title: 'Мастер и&nbsp;Маргарита',
    author: 'Михаил Булгаков',
    rating: 3,
    date: '2015-10-27',
    image: 'bs-master-i-margarita.jpg',
    cover: 'bc-master-i-margarita.jpg',
    height: '7.87',
  },
  {
    title: 'Марсианин',
    author: 'Энди Вейер',
    rating: 5,
    date: '2015-10-18',
    image: 'bs-marsianin.png',
    cover: 'bc-marsianin.jpg',
    height: '8.19',
  },
  {
    title: 'Похвала скуке',
    author: 'Иосиф Бродский',
    rating: 3,
    date: '2015-09-03',
    image: 'bs-pohvala-skuke.png',
    cover: 'bc-pohvala-skuke.jpg',
    height: '7.087',
  },
  {
    title: 'Преступление и&nbsp;наказание',
    author: 'Фёдор Достоевский',
    rating: 3,
    date: '2015-08-01',
    image: 'bs-prestuplenie-i-nakazanie.jpg',
    cover: 'bc-prestuplenie-i-nakazanie.jpg',
    height: '7.87',
  },
  {
    title: 'Планета людей',
    author: 'Антуан де&nbsp;Сент-Экзюпери',
    rating: 4,
    date: '2015-03-16',
    image: 'bs-planeta-lyudei-malenkii-princ.jpg',
    cover: 'bc-planeta-lyudei-malenkii-princ.jpg',
    height: '7.87',
  },
  {
    title: 'Понедельник начинается в&nbsp;субботу',
    author: 'А.&nbsp;Стругацкий, Б.&nbsp;Стругацкий',
    rating: 3,
    date: '2015-02-26',
    image: 'bs-ponedelnik.png',
    cover: 'bc-ponedelnik.jpeg',
    height: '7.87',
  },
  {
    title: 'Полковнику никто не&nbsp;пишет',
    author: 'Габриэль Гарсиа Маркес',
    rating: 2,
    date: '2015-01-20',
    image: 'bs-polkovniku-nikto-ne-pishet.png',
    cover: 'bc-polkovniku-nikto-ne-pishet.jpg',
    height: '7.087',
  },
  {
    title: 'Исчезнувшая',
    author: 'Гиллиан Флинн',
    rating: 3,
    date: '2015-01-01',
    image: 'bs-gone-girl.png',
    cover: 'bc-gone-girl.jpg',
    height: '8.66',
  },
  {
    title: 'Атлант расправил плечи',
    author: 'Айн Рэнд',
    rating: 4,
    date: '2014-12-01',
    image: 'bs-atlant.png',
    cover: 'bc-atlant.jpg',
    height: '8.27',
  },
  {
    title: 'А&nbsp;зори здесь тихие...',
    author: 'Борис Васильев',
    rating: 5,
    date: '2014-10-02',
    image: 'bs-a-zori-zdes-tihie.jpg',
    cover: 'bc-a-zori-zdes-tihie.jpg',
    height: '7.87',
  },
  {
    title: 'Герой нашего времени',
    author: 'Михаил Лермонтов',
    rating: 5,
    date: '2014-09-29',
    image: 'bs-geroi-nashego-vremeni.png',
    cover: 'bc-geroi-nashego-vremeni.jpg',
    height: '7.087',
  },
  {
    title: 'Бесприданница',
    author: 'Александр Островский',
    rating: 4,
    date: '2014-09-26',
    image: 'bs-bespridannica.png',
    cover: 'bc-bespridannica.jpg',
    height: '8.46',
  },
  {
    title: 'У',
    author: 'Эрленд Лу',
    rating: 4,
    date: '2014-09-21',
    image: 'bs-u.jpg',
    cover: 'bc-u.jpg',
    height: '7.87',
  },
  {
    title: 'Во власти женщины',
    author: 'Эрленд Лу',
    rating: 2,
    date: '2014-09-02',
    image: 'bs-vo-vlasti-zhenshiny.jpg',
    cover: 'bc-vo-vlasti-zhenshiny.jpg',
    height: '6.5',
  },
  {
    title: 'Трое в&nbsp;лодке, не&nbsp;считая собаки',
    author: 'Джером К.&nbsp;Джером',
    rating: 2,
    date: '2014-07-23',
    image: 'bs-three-men-in-a-boat.jpg',
    cover: 'bc-three-men-in-a-boat.jpg',
    height: '7.087',
  },
  {
    title: 'Иностранка',
    author: 'Сергей Довлатов',
    rating: 2,
    date: '2014-07-05',
    image: 'bs-inostranka.jpg',
    cover: 'bc-inostranka.jpg',
    height: '7.087',
  },
  {
    title: 'На дороге',
    author: 'Джек Керуак',
    rating: 2,
    date: '2014-06-30',
    image: 'bs-on-the-road.jpeg',
    cover: 'bc-on-the-road.jpeg',
    height: '7.87',
  },
  {
    title: 'Убить пересмешника',
    author: 'Харпер Ли',
    rating: 5,
    date: '2014-05-30',
    image: 'bs-to-kill-a-mockingbird.jpg',
    cover: 'bc-to-kill-a-mockingbird.jpg',
    height: '7.87',
  },
  {
    title: 'Жутко громко &amp;&nbsp;запредельно близко',
    author: 'Джонатан Сафран Фоер',
    rating: 4,
    date: '2014-05-04',
    image: 'bs-extremely-loud-and-incredibly-close.jpg',
    cover: 'bc-extremely-loud-and-incredibly-close.jpg',
    height: '8.35',
  },
  {
    title: 'Хорошо быть тихоней',
    author: 'Стивен Чбоски',
    rating: 5,
    date: '2014-02-01',
    image: 'bs-perks-of-being-a-wallflower.jpg',
    cover: 'bc-perks-of-being-a-wallflower.jpg',
    height: '7.087',
  },
  {
    title: 'Обломов',
    author: 'Иван Гончаров',
    rating: 5,
    date: '2014-02-01',
    image: 'bs-oblomov.jpg',
    cover: 'bc-oblomov.jpg',
    height: '7.87',
  },
  {
    title: 'Цветы для Элджернона',
    author: 'Дэниел Киз',
    rating: 5,
    date: '2013-12-01',
    image: 'bs-flowers-for-algernon.jpg',
    cover: 'bc-flowers-for-algernon.jpg',
    height: '6.5',
  },
  {
    title: 'Маленький принц',
    author: 'Антуан де&nbsp;Сент-Экзюпери',
    rating: 3,
    date: '2013-12-01',
    image: 'bs-le-petite-prince.jpg',
    cover: 'bc-le-petite-prince.jpg',
    height: '7.87',
  },
  {
    title: 'Республика ШКИД',
    author: 'Л.&nbsp;Пантелеев, Г.&nbsp;Белых',
    rating: 5,
    date: '2013-12-01',
    image: 'bs-respublika-shkid.jpg',
    cover: 'bc-respublika-shkid.jpg',
    height: '7.87',
  },
  // {
  //   title: 'Кондуит и&nbsp;Швамбрания',
  //   author: 'Лев Кассиль',
  //   rating: 5,
  //   date: '2013-11-01',
  //   image: 'bs-kondiut-i-shvambrianiya.jpg',
  //   cover: 'bc-kondiut-i-shvambrianiya.jpg',
  //   height: '7.87',
  // },
  {
    title: '1984',
    author: 'Джордж Оруэлл',
    rating: 5,
    date: '2013-11-01',
    image: 'bs-1984.jpg',
    cover: 'bc-1984.jpg',
    height: '7.087',
  },
  {
    title: 'Скотный двор',
    author: 'Джордж Оруэлл',
    rating: 4,
    date: '2013-09-01',
    image: 'bs-animal-farm.jpg',
    cover: 'bc-animal-farm.jpg',
    height: '7.087',
  },
  {
    title: 'Наивно. Супер',
    author: 'Эрленд Лу',
    rating: 5,
    date: '2013-08-01',
    image: 'bs-naivno-super.jpg',
    cover: 'bc-naivno-super.jpg',
    height: '7.87',
  },
  {
    title: 'Портрет Дориана Грея',
    author: 'Оскар Уайльд',
    rating: 4,
    date: '2013-08-01',
    image: 'bs-dorian-grey.jpg',
    cover: 'bc-dorian-grey.jpg',
    height: '8.35',
  },
  {
    title: 'Убийство на&nbsp;улице Морг',
    author: 'Эдгар Аллан По',
    rating: 2,
    date: '2013-07-01',
    image: 'bs-morg-street.jpg',
    cover: 'bc-morg-street.jpg',
    height: '7.087',
  },
  {
    title: 'Моя любимая жена',
    author: 'Тони Парсонс',
    rating: 2,
    date: '2013-06-01',
    image: 'bs-my-favorite-wife.jpg',
    cover: 'bc-my-favorite-wife.jpg',
    height: '7.087',
  },
  {
    title: 'Чемодан',
    author: 'Сергей Довлатов',
    rating: 4,
    date: '2013-06-01',
    image: 'bs-chemodan.jpeg',
    cover: 'bc-chemodan.jpg',
    height: '7.087',
  },
  {
    title: 'Солярис',
    author: 'Станислав Лем',
    rating: 2,
    date: '2013-05-01',
    image: 'bs-solaris.jpeg',
    cover: 'bc-solaris.jpeg',
    height: '7.48',
  },
  {
    title: 'Великий Гэтсби',
    author: 'Фрэнсис Скотт Фицджеральд',
    rating: 4,
    date: '2013-05-01',
    image: 'bs-great-gatsby.jpg',
    cover: 'bc-great-gatsby.jpg',
    height: '7.87',
  },
  {
    title: '11/22/63',
    author: 'Стивен Кинг',
    rating: 4,
    date: '2013-04-01',
    image: 'bs-11-22-63.jpeg',
    cover: 'bc-11-22-63.jpeg',
    height: '7.28',
  },
  {
    title: 'Над пропастью во&nbsp;ржи',
    author: 'Джером Д.&nbsp;Сэлинджер',
    rating: 4,
    date: '2013-03-01',
    image: 'bs-catcher-in-the-rye.jpg',
    cover: 'bc-catcher-in-the-rye.jpg',
    height: '6.5',
  },
  {
    title: 'Старик и&nbsp;море',
    author: 'Эрнест Хемингуэй',
    rating: 3,
    date: '2013-02-24',
    image: 'bs-old-man-and-the-sea.jpeg',
    cover: 'bc-old-man-and-the-sea.jpeg',
    height: '7.087',
  },
  {
    title: 'Стив Джобс',
    author: 'Уолтер Айзексон',
    rating: 3,
    date: '2012-10-01',
    image: 'bs-steve-jobs.jpg',
    cover: 'bc-steve-jobs.jpeg',
    height: '9.45',
  },
  {
    title: 'Сойка-пересмешница',
    author: 'Сьюзен Коллинз',
    rating: 4,
    date: '2012-06-01',
    image: 'bs-mockingjay.jpeg',
    cover: 'bc-mockingjay.jpeg',
    height: '7.87',
  },
  {
    title: 'И вспыхнет пламя',
    author: 'Сьюзен Коллинз',
    rating: 4,
    date: '2012-05-01',
    image: 'bs-catching-fire.jpeg',
    cover: 'bc-catching-fire.jpeg',
    height: '7.87',
  },
  {
    title: 'Голодные игры',
    author: 'Сьюзен Коллинз',
    rating: 4,
    date: '2012-04-01',
    image: 'bs-hunger-games.jpeg',
    cover: 'bc-hunger-games.jpeg',
    height: '7.87',
  },
  {
    title: 'Марсианские хроники',
    author: 'Рэй Брэдбери',
    rating: 3,
    date: '2012-02-01',
    image: 'bs-martian-chronicles.jpg',
    cover: 'bc-martian-chronicles.jpg',
    height: '6.5',
  },
  {
    title: 'Механизмы радости',
    author: 'Рэй Брэдбери',
    rating: 2,
    date: '2012-01-01',
    image: 'bs-mechanisms-of-joy.jpg',
    cover: 'bc-mechanisms-of-joy.jpg',
    height: '7.87',
  },
  {
    title: 'Приключения Шерлока Холмса',
    author: 'Артур Конан Дойл',
    rating: 3,
    date: '2012-01-01',
    image: 'bs-sherlock-holms.jpg',
    cover: 'bc-sherlock-holms.jpg',
    height: '7.87',
  },
  {
    title: 'Метро 2034',
    author: 'Дмитрий Глуховский',
    rating: 3,
    date: '2009-12-01',
    image: 'bs-metro-2034.jpeg',
    cover: 'bc-metro-2034.jpeg',
    height: '8.46',
  },
  {
    title: 'Метро 2033',
    author: 'Дмитрий Глуховский',
    rating: 4,
    date: '2009-11-01',
    image: 'bs-metro-2033.jpeg',
    cover: 'bc-metro-2033.jpeg',
    height: '8.46',
  },
  {
    title: 'Сумеречный Дозор',
    author: 'Сергей Лукьяненко',
    rating: 4,
    date: '2007-01-01',
    image: 'bs-twilight-watch.png',
    cover: 'bc-twilight-watch.jpeg',
    height: '7.87',
  },
  {
    title: 'Дневной Дозор',
    author: 'Сергей Лукьяненко',
    rating: 4,
    date: '2007-01-01',
    image: 'bs-day-watch.png',
    cover: 'bc-day-watch.jpeg',
    height: '7.87',
  },
  {
    title: 'Ночной Дозор',
    author: 'Сергей Лукьяненко',
    rating: 4,
    date: '2007-01-01',
    image: 'bs-night-watch.png',
    cover: 'bc-night-watch.jpeg',
    height: '7.87',
  },
  {
    title: 'Хроники Нарнии',
    author: 'Клайв С.&nbsp;Льюис',
    rating: 3,
    date: '2008-01-01',
    image: 'bs-chronicles-of-narnia.png',
    cover: 'bc-chronicles-of-narnia.jpeg',
    height: '7.87',
  },
  {
    title: 'Властелин Колец',
    author: 'Джон Р.&nbsp;Р.&nbsp;Толкин',
    rating: 4,
    date: '2007-01-01',
    image: 'bs-lotr.png',
    cover: 'bc-lotr.jpeg',
    height: '7.87',
  },
  {
    title: 'Хоббит',
    author: 'Джон Р.&nbsp;Р.&nbsp;Толкин',
    rating: 4,
    date: '2006-01-01',
    image: 'bs-hobbit.png',
    cover: 'bc-hobbit.jpeg',
    height: '8.15',
  },
  {
    title: 'Гарри Поттер и&nbsp;Дары смерти',
    author: 'Дж. К.&nbsp;Ролинг',
    rating: 4,
    date: '2007-01-01',
    image: 'bs-harry-potter-7.png',
    cover: 'bc-harry-potter-7.jpeg',
    height: '8.25',
  },
  {
    title: 'Гарри Поттер и&nbsp;Принц-полукровка',
    author: 'Дж. К.&nbsp;Ролинг',
    rating: 4,
    date: '2006-01-01',
    image: 'bs-harry-potter-6.png',
    cover: 'bc-harry-potter-6.jpeg',
    height: '8.25',
  },
  {
    title: 'Гарри Поттер и&nbsp;Орден Феникса',
    author: 'Дж. К.&nbsp;Ролинг',
    rating: 4,
    date: '2004-01-01',
    image: 'bs-harry-potter-5.png',
    cover: 'bc-harry-potter-5.jpeg',
    height: '8.25',
  },
  {
    title: 'Гарри Поттер и&nbsp;Кубок огня',
    author: 'Дж. К.&nbsp;Ролинг',
    rating: 4,
    date: '2003-01-01',
    image: 'bs-harry-potter-4.png',
    cover: 'bc-harry-potter-4.jpeg',
    height: '8.25',
  },
  {
    title: 'Гарри Поттер и&nbsp;узник Азкабана',
    author: 'Дж. К.&nbsp;Ролинг',
    rating: 4,
    date: '2002-01-01',
    image: 'bs-harry-potter-3.png',
    cover: 'bc-harry-potter-3.jpeg',
    height: '8.25',
  },
  {
    title: 'Гарри Поттер и&nbsp;Тайная комната',
    author: 'Дж. К.&nbsp;Ролинг',
    rating: 4,
    date: '2001-01-01',
    image: 'bs-harry-potter-2.png',
    cover: 'bc-harry-potter-2.jpeg',
    height: '8.25',
  },
  {
    title: 'Гарри Поттер и&nbsp;философский камень',
    author: 'Дж. К.&nbsp;Ролинг',
    rating: 5,
    date: '2000-01-01',
    image: 'bs-harry-potter-1.png',
    cover: 'bc-harry-potter-1.jpeg',
    height: '8.25',
  },
];

function groupByArray(xs, key) {
  return xs.reduce(function (rv, x) {
    let v = key instanceof Function ? key(x) : x[key];
    let el = rv.find((r) => r && r.key === v);
    if (el) {
      el.values.push(x);
    } else {
      rv.push({ key: v, values: [x] });
    }
    return rv;
  }, []);
}

export default function () {
  const byYear = groupByArray(books, (book) => {
    if (book.date) {
      const year = book.date.slice(0, 4);
      if (Number(year) < 2009) {
        return '< 2009';
      }
      return year;
    }
    return 'Once upon a time...';
  });
  return {
    byYear,
    list: books,
    noSpine: books.filter((b) => !b.image).length,
    noCover: books.filter((b) => !b.cover).length,
  };
}
