const books = [
  {
    title: "Саша, привет!",
    author: "Дмитрий Данилов",
    rating: 3,
    date: "2025-02-08",
    image: "bs-sasha-privet.png",
    cover: "bc-sasha-privet.jpg",
    height: "8.15",
  },
  {
    title: "Как жить. Уроки стоицизма от Эпиктета, Сенеки и&nbsp;Марка Аврелия",
    author: "Джон Селларс",
    rating: 3,
    date: "2025-01-25",
    image: "bs-kak-jit.png",
    cover: "bc-kak-jit.jpg",
    height: "7.09",
  },
  {
    title: "Дары волхвов",
    author: "О. Генри",
    rating: 3,
    date: "2025-01-01",
    image: "bs-dary-volkhvov.jpg",
    cover: "bc-dary-volkhvov.jpg",
    height: "7.87",
  },
  {
    title: "Вторая жизнь Уве",
    author: "Фредрик Бакман",
    rating: 4,
    date: "2024-12-29",
    image: "bs-uve.png",
    cover: "bc-uve.jpg",
    height: "8.15",
  },
  {
    title: "Крестный отец",
    author: "Марио Пьюзо",
    rating: "4",
    date: "2024-09-22",
    image: "bs-godfather.jpg",
    cover: "bc-godfather.jpg",
    height: "7.87",
  },
  {
    title: "Потрясающие приключения Кавалера & Клея",
    author: "Майкл Шейбон",
    rating: "4",
    date: "2024-09-06",
    image: "bs-kavaler-clay.png",
    cover: "bc-kavaler-clay.jpg",
    height: "8.27",
  },
  {
    title:
      "Империя должна умереть: История русских революций в лицах. 1900-1917",
    author: "Михаил Зыгарь",
    rating: "3",
    date: "2024-03-07",
    image: "bs-empire-must-die.png",
    cover: "bc-empire-must-die.jpg",
    height: "8.5",
  },
  {
    title: "Silo. Dust",
    author: "Hugh Howey",
    rating: "4",
    date: "2024-01-12",
    image: "bs-silo-dust.png",
    cover: "bc-dust.jpg",
    height: "8.00",
  },
  {
    title: "Бункер. Смена",
    author: "Хью Хауи",
    rating: "4",
    date: "2023-12-13",
    image: "bs-bunker-change.png",
    height: "8.11",
  },
  {
    title: "Бункер. Иллюзия",
    author: "Хью Хауи",
    rating: "4",
    date: "2023-08-18",
    image: "bs-bunker-illusion.png",
    height: "8.11",
  },
  {
    title: "Защита Лужина",
    author: "Владимир Набоков",
    rating: "3",
    date: "2022-07-31",
    image: "bs-luzin.png",
    height: "8.19",
  },
  {
    title: "Конец Вечности",
    author: "Айзек Азимов",
    rating: "5",
    date: "2022-06-09",
    image: "bs-end-of-eternity.png",
    height: "8.11",
  },
  {
    title: "Палата №6",
    author: "Антон Чехов",
    rating: "4",
    date: "2022-01-14",
    image: "bs-palata-6.jpg",
    cover: "bc-palata-6.jpg",
    height: "7.87",
  },
  {
    title: "О чем я говорю, когда говорю о беге",
    author: "Харуки Мураками",
    rating: "5",
    date: "2021-12-01",
    image: "bs-beg.png",
    cover: "bc-beg.jpg",
    height: "7.87",
  },
  {
    title: "Ложная слепота",
    author: "Питер Уоттс",
    rating: "4",
    date: "2019-08-24",
    image: "bs-blindsight.png",
    height: "8.07",
  },
  {
    title: "Географ глобус пропил",
    author: "Алексей Иванов",
    rating: "5",
    date: "2019-06-11",
    image: "bs-geograf.png",
    height: "8.35",
  },
  {
    title: "Имею скафандр – готов путешествовать!",
    author: "Роберт Хайнлайн",
    rating: "5",
    date: "2019-02-08",
    image: "bs-skafandr.png",
    height: "6.5",
  },
  {
    title: "Девять принцев Амбера",
    author: "Роджер Желязны",
    rating: "3",
    date: "2018-12-01",
    image: "bs-9-amber.png",
    cover: "bc-9-amber.jpg",
    height: "8.19",
  },
  {
    title: "Вы, конечно, шутите, мистер Фейнман!",
    author: "Ричард Ф. Фейнман",
    rating: "5",
    date: "2018-08-13",
    image: "bs-feynman.webp",
    cover: "bc-feynman.jpeg",
    height: "7.08",
  },
  {
    title: "Первому игроку приготовиться",
    author: "Эрнест Клайн",
    rating: "4",
    date: "2017-11-15",
    image: "bs-ready-player-one.png",
    height: "9.53",
  },
  {
    title: "Финансист",
    author: "Теодор Драйзер",
    rating: "3",
    date: "2017-05-15",
    image: "bs-finansist.png",
    height: "7.48",
  },
  {
    title: "Источник",
    author: "Айн Рэнд",
    rating: "4",
    date: "2017-03-18",
    image: "bs-istochnik.png",
    height: "8.27",
  },
  {
    title: "Игра престолов",
    author: "Джордж Мартин",
    rating: "4",
    date: "2016-09-10",
    image: "bs-game-of-thrones.png",
    height: "8.54",
  },
  {
    title: "Вся кремлевская рать. Краткая история современной России",
    author: "Михаил Зыгарь",
    rating: "3",
    date: "2016-04-01",
    image: "bs-vsya-kremlevskaya-rat.png",
    height: "8.5",
  },
  {
    title: "Гарри Поттер и Методы рационального мышления",
    author: "Элиезер Юдковски",
    rating: "5",
    date: "2016-03-01",
    image: "bs-hpmor.png",
    height: "8.27",
  },
  {
    title: "Автостопом по Галактике",
    author: "Дуглас Адамс",
    rating: "3",
    date: "2015-12-01",
    image: "bs-autostop.png",
    height: "7.08",
  },
  {
    title: "Мастер и Маргарита",
    author: "Михаил Булгаков",
    rating: "3",
    date: "2015-10-27",
    image: "bs-master-i-margarita.jpg",
    cover: "bc-master-i-margarita.jpg",
    height: "7.87",
  },
  {
    title: "Марсианин",
    author: "Энди Вейер",
    rating: "5",
    date: "2015-10-18",
    image: "bs-marsianin.png",
    height: "8.19",
  },
  {
    title: "Похвала скуке",
    author: "Иосиф Бродский",
    rating: "3",
    date: "2015-09-03",
    image: "bs-pohvala-skuke.png",
    height: "7.08",
  },
  {
    title: "Преступление и наказание",
    author: "Фёдор Достоевский",
    rating: "3",
    date: "2015-08-01",
    image: "bs-prestuplenie-i-nakazanie.jpg",
    cover: "bc-prestuplenie-i-nakazanie.jpg",
    height: "7.87",
  },
  {
    title: "Планета людей",
    author: "Антуан де Сент-Экзюпери",
    rating: "4",
    date: "2015-03-16",
    image: "bs-planeta-lyudei-malenkii-princ.jpg",
    cover: "bc-planeta-lyudei-malenkii-princ.jpg",
    height: "7.87",
  },
  {
    title: "Понедельник начинается в субботу",
    author: "А. Стругацкий, Б. Стругацкий",
    rating: "3",
    date: "2015-02-26",
    image: "bs-ponedelnik.png",
    height: "7.87",
  },
  {
    title: "Полковнику никто не пишет",
    author: "Габриэль Гарсиа Маркес",
    rating: "2",
    date: "2015-01-20",
    image: "bs-polkovniku-nikto-ne-pishet.png",
    height: "7.08",
  },
  {
    title: "Исчезнувшая",
    author: "Гиллиан Флинн",
    rating: "3",
    date: "2015-01-01",
    image: "bs-gone-girl.png",
    height: "8.66",
  },
  {
    title: "Атлант расправил плечи",
    author: "Айн Рэнд",
    rating: "4",
    date: "2014-12-01",
    image: "bs-atlant.png",
    height: "8.27",
  },
  {
    title: "А зори здесь тихие...",
    author: "Борис Васильев",
    rating: "5",
    date: "2014-10-02",
    image: "bs-a-zori-zdes-tihie.jpg",
    height: "7.87",
  },
  {
    title: "Герой нашего времени",
    author: "Михаил Лермонтов",
    rating: "5",
    date: "2014-09-29",
    image: "bs-geroi-nashego-vremeni.png",
    height: "7.08",
  },
  {
    title: "Бесприданница",
    author: "Александр Островский",
    rating: "4",
    date: "2014-09-26",
    image: "bs-bespridannica.png",
    height: "8.46",
  },
  {
    title: "У",
    author: "Эрленд Лу",
    rating: "4",
    date: "2014-09-21",
  },
  {
    title: "Во власти женщины",
    author: "Эрленд Лу",
    rating: "2",
    date: "2014-09-02",
  },
  {
    title: "Трое в лодке, не считая собаки",
    author: "Джером К. Джером",
    rating: "2",
    date: "2014-07-23",
    image: "bs-troe-v-lodke.jpg",
    height: "7.87",
  },
  {
    title: "Иностранка",
    author: "Сергей Довлатов",
    rating: "2",
    date: "2014-07-05",
  },
  {
    title: "На дороге",
    author: "Джек Керуак",
    rating: "2",
    date: "2014-06-30",
  },
  {
    title: "Убить пересмешника",
    author: "Харпер Ли",
    rating: "5",
    date: "2014-05-30",
  },
  {
    title: "Жутко громко & запредельно близко",
    author: "Джонатан Сафран Фоер",
    rating: "4",
    date: "2014-05-04",
    image: "bs-jutko-gromko.jpg",
    height: "8.35",
  },
  {
    title: "Хорошо быть тихоней",
    author: "Стивен Чбоски",
    rating: "5",
    date: "2014-02-01",
  },
  {
    title: "Обломов",
    author: "Иван Гончаров",
    rating: "5",
    date: "2014-02-01",
    image: "bs-oblomov.jpg",
    cover: "bc-oblomov.jpg",
    height: "7.87",
  },
  {
    title: "Цветы для Элджернона",
    author: "Дэниел Киз",
    rating: "5",
    date: "2013-12-01",
  },
  {
    title: "Маленький принц",
    author: "Антуан де Сент-Экзюпери",
    rating: "3",
    date: "2013-12-01",
  },
  {
    title: "Республика ШКИД",
    author: "Л. Пантелеев, Г. Белых",
    rating: "5",
    date: "2013-12-01",
  },
  {
    title: "1984",
    author: "Джордж Оруэлл",
    rating: "5",
    date: "2013-11-01",
  },
  {
    title: "Скотный двор",
    author: "Джордж Оруэлл",
    rating: "4",
    date: "2013-09-01",
  },
  {
    title: "Наивно. Супер",
    author: "Эрленд Лу",
    rating: "5",
    date: "2013-08-01",
  },
  {
    title: "Портрет Дориана Грея",
    author: "Оскар Уайльд",
    rating: "4",
    date: "2013-08-01",
  },
  {
    title: "Убийства на улице Морг",
    author: "Эдгар Аллан По",
    rating: "2",
    date: "2013-07-01",
  },
  {
    title: "Моя любимая жена",
    author: "Тони Парсонс",
    rating: "2",
    date: "2013-06-01",
  },
  {
    title: "Чемодан",
    author: "Сергей Довлатов",
    rating: "4",
    date: "2013-06-01",
  },
  {
    title: "Солярис",
    author: "Станислав Лем",
    rating: "2",
    date: "2013-05-01",
  },
  {
    title: "Великий Гэтсби",
    author: "Фрэнсис Скотт Фицджеральд",
    rating: "4",
    date: "2013-05-01",
  },
  {
    title: "11/22/63",
    author: "Стивен Кинг",
    rating: "4",
    date: "2013-04-01",
  },
  {
    title: "Над пропастью во ржи",
    author: "Джером Д. Сэлинджер",
    rating: "4",
    date: "2013-03-01",
  },
  {
    title: "Старик и море",
    author: "Эрнест Хемингуэй",
    rating: "3",
    date: "2013-02-24",
  },
  {
    title: "Голодные игры",
    author: "Сьюзен Коллинз",
    rating: "4",
    date: "2012-05-01",
  },
  {
    title: "Марсианские хроники",
    author: "Рэй Брэдбери",
    rating: "3",
    date: "2012-02-01",
  },
  {
    title: "Механизмы радости",
    author: "Рэй Брэдбери",
    rating: "2",
    date: "2012-01-01",
  },
  {
    title: "Приключения Шерлока Холмса",
    author: "Артур Конан Дойл",
    rating: "3",
    date: "2012-01-01",
  },
  {
    title: "Метро 2033",
    author: "Дмитрий Глуховский",
    rating: "4",
    date: "2009-11-01",
  },
  {
    title: "Сумеречный Дозор",
    author: "Сергей Лукьяненко",
    rating: "4",
    date: "2007-01-01",
    image: "bs-twilight-watch.png",
    cover: "bc-twilight-watch.jpeg",
    height: "7.87",
  },
  {
    title: "Дневной Дозор",
    author: "Сергей Лукьяненко",
    rating: "4",
    date: "2007-01-01",
    image: "bs-day-watch.png",
    cover: "bc-day-watch.jpeg",
    height: "7.87",
  },
  {
    title: "Ночной Дозор",
    author: "Сергей Лукьяненко",
    rating: "4",
    date: "2007-01-01",
    image: "bs-night-watch.png",
    cover: "bc-night-watch.jpeg",
    height: "7.87",
  },
  {
    title: "Хроники Нарнии",
    author: "Клайв С. Льюис",
    rating: "3",
    date: "2008-01-01",
    image: "bs-chronicles-of-narnia.png",
    cover: "bc-chronicles-of-narnia.jpeg",
    height: "7.87",
  },
  {
    title: "Властелин Колец",
    author: "Джон Р. Р. Толкин",
    rating: "4",
    date: "2007-01-01",
    image: "bs-lotr.png",
    cover: "bc-lotr.jpeg",
    height: "7.87",
  },
  {
    title: "Хоббит",
    author: "Джон Р. Р. Толкин",
    rating: "4",
    date: "2006-01-01",
    image: "bs-hobbit.png",
    cover: "bc-hobbit.jpeg",
    height: "8.15",
  },
  {
    title: "Гарри Поттер и Дары смерти",
    author: "Дж. К. Ролинг",
    rating: "4",
    date: "2007-01-01",
    image: "bs-harry-potter-7.png",
    cover: "bc-harry-potter-7.jpeg",
    height: "8.25",
  },
  {
    title: "Гарри Поттер и Принц-полукровка",
    author: "Дж. К. Ролинг",
    rating: "4",
    date: "2006-01-01",
    image: "bs-harry-potter-6.png",
    cover: "bc-harry-potter-6.jpeg",
    height: "8.25",
  },
  {
    title: "Гарри Поттер и Орден Феникса",
    author: "Дж. К. Ролинг",
    rating: "4",
    date: "2004-01-01",
    image: "bs-harry-potter-5.png",
    cover: "bc-harry-potter-5.jpeg",
    height: "8.25",
  },
  {
    title: "Гарри Поттер и Кубок огня",
    author: "Дж. К. Ролинг",
    rating: "4",
    date: "2003-01-01",
    image: "bs-harry-potter-4.png",
    cover: "bc-harry-potter-4.jpeg",
    height: "8.25",
  },
  {
    title: "Гарри Поттер и узник Азкабана",
    author: "Дж. К. Ролинг",
    rating: "4",
    date: "2002-01-01",
    image: "bs-harry-potter-3.png",
    cover: "bc-harry-potter-3.jpeg",
    height: "8.25",
  },
  {
    title: "Гарри Поттер и Тайная комната",
    author: "Дж. К. Ролинг",
    rating: "4",
    date: "2001-01-01",
    image: "bs-harry-potter-2.png",
    cover: "bc-harry-potter-2.jpeg",
    height: "8.25",
  },
  {
    title: "Гарри Поттер и философский камень",
    author: "Дж. К. Ролинг",
    rating: "5",
    date: "2000-01-01",
    image: "bs-harry-potter-1.png",
    cover: "bc-harry-potter-1.jpeg",
    height: "8.25",
  },
];

function groupByArray(xs, key) {
  return xs.reduce(function (rv, x) {
    let v = key instanceof Function ? key(x) : x[key];
    let el = rv.find((r) => r && r.key === v);
    if (el) {
      el.values.push(x);
    } else {
      rv.push({ key: v, values: [x] });
    }
    return rv;
  }, []);
}

export default function () {
  const byYear = groupByArray(books, (book) => {
    if (book.date) {
      const year = book.date.slice(0, 4);
      if (Number(year) < 2009) {
        return "< 2009";
      }
      return year;
    }
    return "Once upon a time...";
  });
  return {
    byYear,
    list: books.slice().reverse(),
    noSpine: books.filter((b) => !b.image).length,
    noCover: books.filter((b) => !b.cover).length,
  };
}
